# Generated by Django 4.2.3 on 2024-10-21 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin', '0002_expense_month_expense_year_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Entertainment', 'Entertainment'), ('Transportation', 'Transportation'), ('Savings', 'Savings'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month')},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
