# Generated by Django 4.2.3 on 2024-10-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_budgets_delete_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budgets',
        ),
    ]
