# Generated by Django 4.2.3 on 2024-10-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_alter_expense_date_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='adjusted_amount',
        ),
    ]
